export const ADD_FLIGHT = 'ADD_FLIGHT';
export const ADD_NEW_FLIGHT_NAME = 'ADD_NEW_FLIGHT_NAME';
export const SELECTED_FLIGHT = 'SELECTED_FLIGHT';
export const RESET_SELECTED_FLIGHT = 'RESET_SELECTED_FLIGHT';
export const IS_CREATION_MODE = 'IS_CREATION_MODE';
export const ADD_NEW_COORDINATES = 'ADD_NEW_COORDINATES';
export const RESET_NEW_PLANNING_VALUES = 'RESET_NEW_PLANNING_VALUES';